(() => {
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=n=>Math.abs(n)>=1e6?(n/1e6).toFixed(1)+'M':Math.abs(n)>=1e3?(n/1e3).toFixed(Math.abs(n)>=1e5?0:1)+'k':String(n||0);
  const state={data:null};
  const style=document.createElement('style');style.textContent=`
    .trend-section{padding-top:8px}.trend-grid{display:grid;grid-template-columns:1.35fr 1fr 1fr;gap:14px}.trend-card{position:relative;overflow:hidden;padding:20px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,rgba(255,255,255,.055),rgba(255,255,255,.018));box-shadow:0 18px 55px rgba(0,0,0,.16)}.trend-card.featured{background:linear-gradient(145deg,rgba(124,92,255,.16),rgba(255,255,255,.025))}.trend-card h3{margin:0 0 4px;font:700 18px 'Space Grotesk',Inter}.trend-card>p{margin:0 0 15px;color:var(--muted);font-size:12px}.trend-item{display:grid;grid-template-columns:30px 1fr auto;align-items:center;gap:10px;padding:11px 0;border-top:1px solid var(--line)}.trend-rank{font:800 12px 'Space Grotesk';color:var(--muted)}.trend-name{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--text);font-weight:700;font-size:13px}.trend-growth{font-size:11px;color:#70d6a0;margin-top:3px}.trend-growth.negative{color:#ff8d8d}.trend-score{font:800 12px 'Space Grotesk';text-align:right}.trend-spark{height:28px;margin:8px 0 2px;display:flex;align-items:end;gap:3px}.trend-spark i{display:block;flex:1;height:var(--h);min-height:3px;border-radius:3px 3px 1px 1px;background:currentColor;opacity:.65}.trend-meta{display:flex;gap:10px;color:var(--muted);font-size:11px;margin-top:4px}.trend-empty{padding:24px;border:1px dashed var(--line);border-radius:16px;color:var(--muted);font-size:13px}.trend-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(112,214,160,.1);color:#70d6a0;font-size:10px;font-weight:800;letter-spacing:.04em}.light .trend-card{background:rgba(255,255,255,.7)}
    @media(max-width:900px){.trend-grid{grid-template-columns:1fr 1fr}.trend-card.featured{grid-column:1/-1}}@media(max-width:600px){.trend-grid{grid-template-columns:1fr}.trend-card.featured{grid-column:auto}}
  `;document.head.appendChild(style);
  async function load(){try{const r=await fetch('data/trending.json',{cache:'no-store'});if(!r.ok)throw 0;state.data=await r.json();render()}catch{}}
  function item(r,i,mode){const d=mode==='month'?r.stars_30d:mode==='rising'?r.stars_7d:r.star_delta;const f=mode==='month'?r.forks_30d:mode==='rising'?r.forks_7d:r.fork_delta;const score=mode==='rising'?r.trend_score:r.stars;return `<div class="trend-item"><span class="trend-rank">${String(i+1).padStart(2,'0')}</span><div><a class="trend-name" href="https://github.com/${encodeURIComponent(r.full_name).replace('%2F','/')}" target="_blank" rel="noopener">${esc(r.full_name)}</a><span class="trend-growth ${d<0?'negative':''}">${d>=0?'+':''}${fmt(d)} ★ · ${f>=0?'+':''}${fmt(f)} forks</span></div><span class="trend-score">${mode==='rising'?'⚡ '+fmt(score):'★ '+fmt(score)}</span></div>`}
  function card(title,sub,rows,mode,featured=false){let spark='';if(rows.length){const max=Math.max(...rows.map(x=>Math.max(1,x.stars_7d||x.star_delta||1)));spark=`<div class="trend-spark">${rows.slice(0,12).map(x=>`<i style="--h:${Math.max(8,((x.stars_7d||x.star_delta||1)/max)*100)}%"></i>`).join('')}</div>`}return `<article class="trend-card ${featured?'featured':''}"><span class="trend-badge">${featured?'LIVE TREND':'GITHUB SIGNAL'}</span><h3>${title}</h3><p>${sub}</p>${spark}${rows.slice(0,5).map((r,i)=>item(r,i,mode)).join('')||'<div class="trend-empty">Collecting historical snapshots. Check back after the next scheduled run.</div>'}</article>`}
  function render(){const host=document.querySelector('.spotlight');if(!host||document.getElementById('trendSection'))return;const d=state.data||{};const section=document.createElement('section');section.className='section trend-section';section.id='trendSection';section.innerHTML=`<div class="section-head"><div><span class="section-kicker">HISTORICAL INTELLIGENCE</span><h2>What’s <span>rising.</span></h2></div><p>${d.snapshot_count||0} daily snapshots · 7-day and 30-day growth</p></div><div class="trend-grid">${card('Trending now','Composite growth across stars, forks and watchers.',(d.trending||[]).slice(0,5),'rising',true)}${card('Rising fast','Projects gaining the most stars over the last 7 days.',(d.rising||[]).slice(0,5),'rising')}${card('New & promising','Smaller projects showing fresh momentum.',(d.new_promising||[]).slice(0,5),'day')}</div>`;host.after(section)}
  load();
})();