const API='https://api.github.com/search/repositories';
const CATALOG='data/catalog.json';
const state={all:[],shown:0,platform:'All',query:'',sort:'stars',view:'grid',cacheKey:'open-source-explorer-v2'};
const categories=[{name:'AI & Machine Learning',icon:'✦',q:'AI machine learning'},{name:'Video Editing',icon:'▶',q:'video editor'},{name:'Developer Tools',icon:'⌘',q:'developer tools'},{name:'Productivity',icon:'◫',q:'productivity'},{name:'Design & Creative',icon:'◇',q:'design creative'},{name:'Security',icon:'◉',q:'cybersecurity security'},{name:'Media & Music',icon:'♫',q:'media music player'},{name:'Utilities',icon:'⚙',q:'utility tools'}];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),fmt=n=>n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(n>=1e5?0:1)+'k':String(n||0),ago=d=>{const x=(Date.now()-new Date(d))/864e5;if(x<1)return'today';if(x<30)return Math.floor(x)+'d ago';if(x<365)return Math.floor(x/30)+'mo ago';return Math.floor(x/365)+'y ago'},year=d=>new Date(d).getFullYear();
function apiHeaders(){return{'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}}
async function gh(q,sort='stars',order='desc',per=30){const u=new URL(API);u.searchParams.set('q',q);u.searchParams.set('sort',sort);u.searchParams.set('order',order);u.searchParams.set('per_page',per);const r=await fetch(u,{headers:apiHeaders()});if(!r.ok)throw new Error(r.status===403?'GitHub API rate limit reached.':'GitHub API error');return r.json()}
function unique(items){const m=new Map();items.forEach(x=>m.set(x.id,x));return[...m.values()]}
function normalize(items){return unique(items).map(r=>({...r,_category:r._category||inferCategory(r),_platform:r._platform||inferPlatform(r)}))}
async function loadCatalog(){const r=await fetch(CATALOG,{cache:'no-store'});if(!r.ok)throw new Error('Static catalog unavailable');const d=await r.json();return normalize(d.repositories||[])}
async function discover(){setLoading();let repos=[];let liveOK=false;try{const base=['is:public archived:false stars:>100','is:public archived:false forks:>20'];const results=await Promise.allSettled(categories.map(c=>gh(`${c.q} ${base[0]}`,'stars','desc',30)));repos=unique(results.flatMap(x=>x.status==='fulfilled'?x.value.items:[]));const active=await Promise.allSettled(categories.slice(0,4).map(c=>gh(`${c.q} ${base[1]}`,'updated','desc',25)));repos=unique([...repos,...active.flatMap(x=>x.status==='fulfilled'?x.value.items:[])]);liveOK=repos.length>0}catch(_){}if(!liveOK){try{repos=await loadCatalog();toast('Loaded the built-in open-source catalog. GitHub live discovery will refresh automatically.')}catch(_){const cached=localStorage.getItem(state.cacheKey);if(cached)repos=JSON.parse(cached).items||[]}}if(!repos.length){showError('No repositories are available yet. Refresh after GitHub Actions updates the catalog.');return}state.all=normalize(repos);localStorage.setItem(state.cacheKey,JSON.stringify({time:Date.now(),items:state.all}));renderAll()}
function inferCategory(r){const t=((r.name||'')+' '+(r.description||'')+' '+(r.topics||[]).join(' ')).toLowerCase();if(/ai|llm|machine learning|neural|diffusion/.test(t))return'AI & Machine Learning';if(/video|ffmpeg|editor|obs/.test(t))return'Video Editing';if(/developer|devtool|ide|code|programming|compiler|terminal/.test(t))return'Developer Tools';if(/productiv|note|calendar|task|workflow/.test(t))return'Productivity';if(/design|draw|paint|graphics|3d/.test(t))return'Design & Creative';if(/security|privacy|password|network/.test(t))return'Security';if(/music|audio|podcast|player|media/.test(t))return'Media & Music';return'Utilities'}
function inferPlatform(r){const t=((r.name||'')+' '+(r.description||'')+' '+(r.topics||[]).join(' ')).toLowerCase();if(/android|kotlin|jetpack|apk/.test(t))return'Android';if(/macos|mac os|swift|objective-c|homebrew/.test(t))return'macOS';if(/windows|win32|powershell|wpf|uwp/.test(t))return'Windows';if(/linux|ubuntu|arch linux|wayland|kernel/.test(t))return'Linux';return'Cross-platform'}
function renderAll(){$('#repoCount').textContent=fmt(state.all.length);$('#yearCount').textContent=new Set(state.all.map(r=>year(r.created_at))).size;$('#updateTime').textContent=state.all.length?'Catalog + GitHub':'Offline';renderCategories();renderSignals();renderFilters();renderDirectory()}
function renderCategories(){$('#categoryRow').innerHTML=categories.map(c=>`<button class="cat" data-category="${esc(c.name)}"><span class="cat-icon">${c.icon}</span><b>${esc(c.name)}</b><span>Explore repositories →</span></button>`).join('');document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{state.query=b.dataset.category;$('#searchInput').value=state.query;document.querySelector('#all-tools').scrollIntoView({behavior:'smooth'});renderDirectory()})}
function mini(items){return items.slice(0,4).map((r,i)=>`<a class="mini-item" href="${r.html_url}" target="_blank" rel="noopener"><span class="rank">0${i+1}</span><img class="mini-avatar" src="${r.owner?.avatar_url||''}" loading="lazy" alt=""><div><b>${esc(r.full_name)}</b><span>★ ${fmt(r.stargazers_count)} · ${esc(r.language||'Open source')}</span></div></a>`).join('')||'<div class="mini-item"><span>—</span><div><b>No data yet</b><span>Refresh to retry</span></div></div>'}
function renderSignals(){const recent=[...state.all].sort((a,b)=>new Date(b.pushed_at)-new Date(a.pushed_at));$('#monthlyList').innerHTML=mini(recent);$('#forkList').innerHTML=mini([...state.all].sort((a,b)=>b.forks_count-a.forks_count));$('#watchList').innerHTML=mini([...state.all].sort((a,b)=>b.watchers_count-a.watchers_count));$('#starList').innerHTML=mini([...state.all].sort((a,b)=>b.stargazers_count-a.stargazers_count))}
function renderFilters(){const vals=['All','Android','macOS','Windows','Linux','Cross-platform'];$('#platformFilters').innerHTML=vals.map(v=>`<button class="filter-chip ${state.platform===v?'active':''}" data-platform-filter="${v}">${v}</button>`).join('');document.querySelectorAll('[data-platform-filter]').forEach(b=>b.onclick=()=>{state.platform=b.dataset.platform;state.shown=12;renderFilters();renderDirectory()})}
function filtered(){let x=state.all.filter(r=>state.platform==='All'||r._platform===state.platform);if(state.query)x=x.filter(r=>`${r.full_name} ${r.name||''} ${r.description||''} ${(r.topics||[]).join(' ')} ${r._category} ${r._platform}`.toLowerCase().includes(state.query.toLowerCase()));const key=state.sort;if(key==='newest')x.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));else if(key==='updated')x.sort((a,b)=>new Date(b.pushed_at)-new Date(a.pushed_at));else if(key==='forks')x.sort((a,b)=>b.forks_count-a.forks_count);else if(key==='watchers')x.sort((a,b)=>b.watchers_count-a.watchers_count);else x.sort((a,b)=>b.stargazers_count-a.stargazers_count);return x}
function card(r){const topics=(r.topics||[]).slice(0,3),saved=JSON.parse(localStorage.getItem('os-saved')||'[]').includes(r.id),compared=JSON.parse(localStorage.getItem('os-compare')||'[]').includes(r.id);return `<article class="repo-card" data-repo-id="${r.id}"><div class="repo-top"><div><a class="repo-name" href="${r.html_url}" target="_blank" rel="noopener">${esc(r.name)}</a><div class="repo-owner">${esc(r.owner?.login||'')} · ${r._platform}</div></div><span class="repo-tag">${esc(r._category.split(' ')[0])}</span></div><p class="repo-desc">${esc(r.description||'No description provided.')}</p><div class="repo-tags">${topics.map(t=>`<span class="repo-tag">#${esc(t)}</span>`).join('')}</div><div class="repo-meta"><span>★ <b>${fmt(r.stargazers_count)}</b></span><span>⑂ <b>${fmt(r.forks_count)}</b></span><span>◉ <b>${fmt(r.watchers_count)}</b></span><span>↻ ${ago(r.pushed_at)}</span></div><div class="repo-actions"><button class="save-repo ${saved?'active':''}" data-save="${r.id}">${saved?'♥':'♡'} Save</button><button class="compare-repo ${compared?'active':''}" data-compare="${r.id}">${compared?'✓':'＋'} Compare</button></div></article>`}
function renderDirectory(){const x=filtered(),batch=state.shown||12,visible=x.slice(0,batch);$('#activeFilter').textContent=`${state.platform} · ${state.query||'All tools'} · ${x.length} found`;$('#directory').className=`directory-grid ${state.view==='list'?'directory-list':''}`;if(!visible.length){$('#directory').innerHTML='';$('#emptyState').classList.remove('hidden');$('#loadMoreWrap').classList.add('hidden');return}$('#emptyState').classList.add('hidden');$('#loadMoreWrap').classList.toggle('hidden',visible.length>=x.length);let html='',last='';visible.forEach(r=>{const y=year(r.created_at);if(state.sort==='newest'||!state.query){if(y!==last){html+=`<div class="year-label">${y} <span>— repositories created this year</span></div>`;last=y}}html+=card(r)});$('#directory').innerHTML=html}
function setLoading(){['monthlyList','forkList','watchList','starList'].forEach(id=>$(id).innerHTML='<div class="loading"></div><div class="loading"></div><div class="loading"></div>')}
function showError(m){$('#directory').innerHTML=`<div class="empty-state"><div>⚠</div><h3>Repository catalog could not load</h3><p>${esc(m)}</p><button class="load-more" onclick="discover()">Try again</button></div>`}function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
$('#searchInput').addEventListener('input',e=>{state.query=e.target.value.trim();state.shown=12;renderDirectory()});$('#sortSelect').onchange=e=>{state.sort=e.target.value;state.shown=12;renderDirectory()};$('#loadMore').onclick=()=>{state.shown=(state.shown||12)+12;renderDirectory()};$('#refreshBtn').onclick=()=>{localStorage.removeItem(state.cacheKey);state.shown=12;discover()};$('#clearFilters').onclick=()=>{state.platform='All';state.query='';$('#searchInput').value='';state.shown=12;renderFilters();renderDirectory()};$('#gridBtn').onclick=()=>{state.view='grid';$('#gridBtn').classList.add('active');$('#listBtn').classList.remove('active');renderDirectory()};$('#listBtn').onclick=()=>{state.view='list';$('#listBtn').classList.add('active');$('#gridBtn').classList.remove('active');renderDirectory()};document.querySelectorAll('.platform-card').forEach(b=>b.onclick=()=>{state.platform=b.dataset.platform;state.shown=12;renderFilters();document.querySelector('#all-tools').scrollIntoView({behavior:'smooth'});renderDirectory()});document.querySelectorAll('.quick-tags button').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.query;state.query=b.dataset.query;state.shown=12;document.querySelector('#all-tools').scrollIntoView({behavior:'smooth'});renderDirectory()});$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('os-light',document.body.classList.contains('light'))};window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}});if(localStorage.getItem('os-light')==='true')document.body.classList.add('light');state.shown=12;discover();