(() => {
  const API = 'https://api.github.com';
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt = n => n >= 1e6 ? (n/1e6).toFixed(1)+'M' : n >= 1e3 ? (n/1e3).toFixed(n>=1e5?0:1)+'k' : String(n || 0);
  const headers = {'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};

  const style = document.createElement('style');
  style.textContent = `
  .repo-modal{position:fixed;inset:0;z-index:50;background:rgba(3,4,7,.78);backdrop-filter:blur(18px);display:none;padding:24px;overflow:auto}
  .repo-modal.open{display:flex;align-items:flex-start;justify-content:center}.repo-sheet{width:min(1080px,100%);margin:auto;background:#0d1016;border:1px solid rgba(255,255,255,.12);border-radius:28px;box-shadow:0 35px 100px #000b;overflow:hidden}.repo-head{padding:25px 28px;border-bottom:1px solid rgba(255,255,255,.08);display:flex;justify-content:space-between;gap:20px}.repo-head-main{min-width:0}.repo-kicker{color:#8f83e8;font-size:10px;letter-spacing:.14em;font-weight:800}.repo-title{font:700 30px 'Space Grotesk';margin:7px 0}.repo-full{font-size:11px;color:#747d8d}.repo-close{width:40px;height:40px;border-radius:12px;border:1px solid rgba(255,255,255,.1);background:#171a22;color:#fff}.repo-body{display:grid;grid-template-columns:1fr 300px}.repo-main{padding:27px}.repo-side{padding:27px;border-left:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.018)}.repo-description{font-size:15px;line-height:1.7;color:#b4bbc7;margin:0 0 22px}.repo-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:25px}.repo-stat{border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:14px;background:rgba(255,255,255,.025)}.repo-stat b{display:block;font:700 19px 'Space Grotesk'}.repo-stat span{display:block;color:#737c8c;font-size:9px;margin-top:3px}.repo-actions{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:26px}.repo-action{padding:10px 14px;border-radius:11px;background:#7560e8;color:#fff;font-size:11px;border:1px solid #7560e8}.repo-action.secondary{background:rgba(255,255,255,.05);border-color:rgba(255,255,255,.1)}.repo-section-title{font:700 14px 'Space Grotesk';margin:25px 0 11px}.readme{border:1px solid rgba(255,255,255,.08);border-radius:15px;background:#090b0f;padding:18px;color:#aeb5c1;font:12px/1.7 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;max-height:430px;overflow:auto}.repo-side h3{font:700 14px 'Space Grotesk';margin:0 0 14px}.repo-meta-row{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.06);font-size:10px}.repo-meta-row span{color:#737c8b}.repo-topics{display:flex;flex-wrap:wrap;gap:5px}.repo-topic{padding:5px 8px;border-radius:7px;background:rgba(124,92,255,.1);color:#9d90ef;font-size:9px}.release{padding:11px 0;border-bottom:1px solid rgba(255,255,255,.06)}.release b{display:block;font-size:11px}.release span{font-size:9px;color:#70798a}.repo-loading{padding:70px;text-align:center;color:#7f8795;font-size:12px}.repo-error{padding:70px;text-align:center;color:#a5adba}.repo-error b{display:block;color:#fff;font-size:15px;margin-bottom:5px}@media(max-width:760px){.repo-modal{padding:10px}.repo-sheet{border-radius:20px}.repo-head{padding:20px}.repo-body{grid-template-columns:1fr}.repo-side{border-left:0;border-top:1px solid rgba(255,255,255,.08)}.repo-main,.repo-side{padding:20px}.repo-title{font-size:24px}.repo-stats{grid-template-columns:repeat(2,1fr)}}`;
  document.head.appendChild(style);

  const modal = document.createElement('div');
  modal.className = 'repo-modal';
  modal.innerHTML = `<div class="repo-sheet"><div id="repoDetailContent" class="repo-loading">Loading repository…</div></div>`;
  document.body.appendChild(modal);

  async function get(url){ const r=await fetch(API+url,{headers}); if(!r.ok) throw new Error('GitHub API request failed'); return r.json(); }
  function markdownToText(md){ return String(md||'').replace(/```[\s\S]*?```/g, m=>m.replace(/```[^\n]*\n?/,'').replace(/```$/,'')).replace(/!\[[^\]]*\]\([^)]*\)/g,'').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#{1,6}\s*/gm,'').replace(/[*_`>]/g,'').replace(/\n{3,}/g,'\n\n').slice(0,12000); }
  function openRepo(full){
    const [owner,name]=full.split('/'); if(!owner||!name)return;
    history.pushState({repo:full},'',`?repo=${encodeURIComponent(full)}`); modal.classList.add('open'); document.body.style.overflow='hidden';
    $('#repoDetailContent').innerHTML='<div class="repo-loading">Loading repository intelligence…</div>';
    Promise.all([get(`/repos/${owner}/${name}`),get(`/repos/${owner}/${name}/readme`).catch(()=>null),get(`/repos/${owner}/${name}/releases?per_page=5`).catch(()=>[])])
      .then(([r,readme,releases])=>render(r,readme,releases)).catch(e=>$('#repoDetailContent').innerHTML=`<div class="repo-error"><b>Could not load repository</b>${esc(e.message)}</div>`);
  }
  function render(r,readme,releases){
    const topics=r.topics||[];
    $('#repoDetailContent').innerHTML=`<div class="repo-head"><div class="repo-head-main"><div class="repo-kicker">OPEN SOURCE REPOSITORY</div><div class="repo-title">${esc(r.name)}</div><div class="repo-full">${esc(r.full_name)} · ${esc(r.license?.spdx||'License not detected')}</div></div><button class="repo-close" id="repoClose">×</button></div><div class="repo-body"><main class="repo-main"><p class="repo-description">${esc(r.description||'No description provided.')}</p><div class="repo-stats"><div class="repo-stat"><b>${fmt(r.stargazers_count)}</b><span>Stars</span></div><div class="repo-stat"><b>${fmt(r.forks_count)}</b><span>Forks</span></div><div class="repo-stat"><b>${fmt(r.watchers_count)}</b><span>Watchers</span></div><div class="repo-stat"><b>${fmt(r.open_issues_count)}</b><span>Open issues</span></div></div><div class="repo-actions"><a class="repo-action" href="${r.html_url}" target="_blank" rel="noopener">Open on GitHub ↗</a><a class="repo-action secondary" href="${r.clone_url}" target="_blank" rel="noopener">Clone URL</a></div><div class="repo-section-title">README preview</div><div class="readme">${esc(readme ? markdownToText(atob(readme.content.replace(/\n/g,''))) : 'README not available.')}</div></main><aside class="repo-side"><h3>Repository details</h3><div class="repo-meta-row"><span>Language</span><b>${esc(r.language||'—')}</b></div><div class="repo-meta-row"><span>Created</span><b>${new Date(r.created_at).getFullYear()}</b></div><div class="repo-meta-row"><span>Updated</span><b>${new Date(r.pushed_at).toLocaleDateString()}</b></div><div class="repo-meta-row"><span>Size</span><b>${fmt(r.size)} KB</b></div><div class="repo-section-title">Topics</div><div class="repo-topics">${topics.length?topics.map(t=>`<span class="repo-topic">#${esc(t)}</span>`).join(''):'<span class="repo-meta-row"><span>No topics</span></span>'}</div><div class="repo-section-title">Latest releases</div>${releases?.length?releases.map(x=>`<div class="release"><b>${esc(x.name||x.tag_name)}</b><span>${new Date(x.published_at||x.created_at).toLocaleDateString()}</span></div>`).join(''):'<div class="repo-meta-row"><span>No releases found</span></div>'}</aside></div>`;
    $('#repoClose').onclick=close;
  }
  function close(){modal.classList.remove('open');document.body.style.overflow='';if(location.search.includes('repo=')){history.pushState({},'',location.pathname+location.hash)}}
  function $(s){return modal.querySelector(s)}
  document.addEventListener('click',e=>{const a=e.target.closest('.repo-name');if(a){const url=new URL(a.href);const full=url.pathname.split('/').filter(Boolean).slice(0,2).join('/');if(full.includes('/')){e.preventDefault();openRepo(full)}}});
  modal.addEventListener('click',e=>{if(e.target===modal)close()});
  window.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
  window.addEventListener('popstate',()=>{const q=new URLSearchParams(location.search).get('repo');if(q)openRepo(q);else close()});
  const initial=new URLSearchParams(location.search).get('repo'); if(initial)openRepo(initial);
})();