(() => {
  const API='https://api.github.com';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=n=>n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(n>=1e5?0:1)+'k':String(n||0);
  const headers={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};
  const root=document.querySelector('#toolPage'); if(!root)return;
  const get=u=>fetch(API+u,{headers}).then(r=>{if(!r.ok)throw Error('GitHub request failed');return r.json()});
  const text=md=>String(md||'').replace(/```[\s\S]*?```/g,'').replace(/!\[[^\]]*\]\([^)]*\)/g,'').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#{1,6}\s*/gm,'').replace(/[*_`>]/g,'').replace(/\n{3,}/g,'\n\n').slice(0,14000);
  const repoParam=new URLSearchParams(location.search).get('repo');
  const full=repoParam||''; const [owner,name]=full.split('/');
  const styles=`<style>.tool-page{max-width:1100px;margin:auto;padding:55px 28px 90px}.tool-hero{padding:30px 0 35px;border-bottom:1px solid var(--line)}.tool-kicker{font-size:10px;font-weight:800;letter-spacing:.15em;color:#9a8cff}.tool-title{font:700 clamp(40px,6vw,72px)/1 'Space Grotesk';letter-spacing:-.05em;margin:10px 0}.tool-full{font-size:12px;color:var(--muted)}.tool-desc{max-width:760px;color:#9ba3b2;font-size:16px;line-height:1.7;margin:18px 0 25px}.tool-actions{display:flex;gap:9px;flex-wrap:wrap}.tool-btn{border:1px solid var(--line);background:var(--panel2);padding:11px 16px;border-radius:11px;font-size:12px}.tool-btn.primary{background:#7560e8;border-color:#7560e8;color:#fff}.tool-content{display:grid;grid-template-columns:1fr 290px;gap:28px;padding-top:30px}.tool-section{border:1px solid var(--line);border-radius:18px;padding:20px;background:rgba(255,255,255,.025);margin-bottom:14px}.tool-section h2{font:700 16px 'Space Grotesk';margin:0 0 15px}.install-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.install{display:flex;align-items:center;justify-content:space-between;padding:14px;border:1px solid var(--line);border-radius:13px;background:var(--panel2)}.install b{font-size:12px}.install small{display:block;color:#737b89;font-size:9px;margin-top:2px}.install a{font-size:10px;color:#a99cff}.readme{white-space:pre-wrap;color:#9ca4b2;font:12px/1.7 ui-monospace,SFMono-Regular,Consolas,monospace;max-height:600px;overflow:auto}.meta-row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--line);font-size:11px}.meta-row span{color:#737b89}.topics{display:flex;flex-wrap:wrap;gap:6px}.topic{font-size:9px;color:#a295ff;background:rgba(124,92,255,.1);padding:5px 8px;border-radius:7px}.stat-row{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:20px 0}.stat{padding:13px;border:1px solid var(--line);border-radius:12px}.stat b{display:block;font:700 18px 'Space Grotesk'}.stat span{font-size:9px;color:#737b89}.tool-loading,.tool-error{text-align:center;padding:100px 20px;color:#7d8593}.tool-error b{display:block;color:var(--text);font-size:16px;margin-bottom:5px}.copy-ok{opacity:.7}@media(max-width:760px){.tool-page{padding:35px 16px 60px}.tool-content{grid-template-columns:1fr}.install-grid{grid-template-columns:1fr}.stat-row{grid-template-columns:repeat(2,1fr)}.tool-title{font-size:46px}}</style>`;
  function installLinks(r){const text=((r.name||'')+' '+(r.description||'')+' '+(r.topics||[]).join(' ')).toLowerCase();const links=[];if(/android|apk/.test(text))links.push(['Android',`https://github.com/${r.full_name}/releases`]);if(/macos|mac os|swift|objective-c/.test(text))links.push(['macOS',r.html_url]);if(/windows|win32|powershell|wpf|uwp/.test(text))links.push(['Windows',`https://github.com/${r.full_name}/releases`]);if(/web|browser|self-hosted|server|cloud/.test(text)||!links.length)links.push(['Web / Online',r.homepage||r.html_url]);if(!links.some(x=>x[0]==='GitHub'))links.push(['GitHub',r.html_url]);return links;}
  function health(r,releases){let s=0;s+=Math.min(25,Math.log10(1+(r.stargazers_count||0))*5);s+=Math.min(20,Math.log10(1+(r.forks_count||0))*4);s+=(r.license?15:5);s+=(r.description?10:2);s+=((r.topics||[]).length?10:3);s+=(releases.length?20:5);return Math.min(100,Math.round(s));}
  async function load(){if(!owner||!name){root.innerHTML=styles+'<div class="tool-error"><b>Tool not found</b><p>Choose a repository from the directory.</p></div>';return}try{const [r,readme,releases]=await Promise.all([get(`/repos/${owner}/${name}`),get(`/repos/${owner}/${name}/readme`).catch(()=>null),get(`/repos/${owner}/${name}/releases?per_page=5`).catch(()=>[])]);render(r,readme,releases)}catch(e){root.innerHTML=styles+`<div class="tool-error"><b>Could not load tool</b><p>${esc(e.message)}</p></div>`}}
  function render(r,readme,releases){const installs=installLinks(r),topics=r.topics||[];root.innerHTML=styles+`<div class="tool-page"><section class="tool-hero"><div class="tool-kicker">OPEN SOURCE TOOL</div><h1 class="tool-title">${esc(r.name)}</h1><div class="tool-full">${esc(r.full_name)} · ${esc(r.license?.spdx||r.license?.name||'License not detected')}</div><p class="tool-desc">${esc(r.description||'Open-source project from GitHub.')}</p><div class="tool-actions"><a class="tool-btn primary" href="${esc(r.html_url)}" target="_blank" rel="noopener">Jump to GitHub ↗</a><button class="tool-btn" id="cloneBtn">Copy clone URL</button></div><div class="stat-row"><div class="stat"><b>${fmt(r.stargazers_count)}</b><span>Stars</span></div><div class="stat"><b>${fmt(r.forks_count)}</b><span>Forks</span></div><div class="stat"><b>${fmt(r.watchers_count)}</b><span>Watchers</span></div><div class="stat"><b>${health(r,releases)}%</b><span>Project health</span></div></div></section><div class="tool-content"><main><section class="tool-section"><h2>Install / Use</h2><div class="install-grid">${installs.map(([label,url])=>`<div class="install"><div><b>${esc(label)}</b><small>${label==='Web / Online'?'Open in browser':'Download / setup'}</small></div><a href="${esc(url)}" target="_blank" rel="noopener">Open ↗</a></div>`).join('')}</div></section><section class="tool-section"><h2>README</h2><div class="readme">${esc(readme?text(atob(readme.content.replace(/\n/g,''))):'README is not available.')}</div></section></main><aside><section class="tool-section"><h2>Details</h2><div class="meta-row"><span>Language</span><b>${esc(r.language||'—')}</b></div><div class="meta-row"><span>Size</span><b>${fmt(r.size)} KB</b></div><div class="meta-row"><span>Issues</span><b>${fmt(r.open_issues_count)}</b></div><div class="meta-row"><span>Default branch</span><b>${esc(r.default_branch||'—')}</b></div><h2 style="margin-top:22px">Topics</h2><div class="topics">${topics.length?topics.map(t=>`<span class="topic">#${esc(t)}</span>`).join(''):'No topics'}</div></section><section class="tool-section"><h2>Latest releases</h2>${releases.length?releases.slice(0,5).map(x=>`<div class="meta-row"><span>${esc(x.tag_name||x.name)}</span><a href="${esc(x.html_url)}" target="_blank" rel="noopener">View ↗</a></div>`).join(''):'<div class="meta-row"><span>No releases found</span></div>'}</section></aside></div></div>`;document.getElementById('cloneBtn').onclick=async()=>{try{await navigator.clipboard.writeText(r.clone_url);document.getElementById('cloneBtn').textContent='Copied ✓';setTimeout(()=>document.getElementById('cloneBtn').textContent='Copy clone URL',1500)}catch{}}}
  load();
})();