(() => {
  const API='https://api.github.com';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=n=>n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(n>=1e5?0:1)+'k':String(n||0);
  const headers={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};
  const root=document.querySelector('#toolPage'); if(!root)return;
  const get=u=>fetch(API+u,{headers}).then(r=>{if(!r.ok)throw Error('GitHub request failed');return r.json()});
  const text=md=>String(md||'').replace(/```[\s\S]*?```/g,'').replace(/!\[[^\]]*\]\([^)]*\)/g,'').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#{1,6}\s*/gm,'').replace(/[*_`>]/g,'').replace(/\n{3,}/g,'\n\n').slice(0,14000);
  const full=new URLSearchParams(location.search).get('repo')||''; const [owner,name]=full.split('/');
  const styles=`<style>.tool-page{max-width:1120px;margin:auto;padding:42px 24px 80px}.tool-hero{padding:20px 0 30px}.tool-kicker{font-size:10px;font-weight:800;letter-spacing:.14em;color:#9183ee}.tool-title{font:700 clamp(42px,6vw,70px)/1 'Space Grotesk';letter-spacing:-.055em;margin:9px 0}.tool-full{font-size:11px;color:var(--muted)}.tool-desc{max-width:780px;color:#9ba3b2;font-size:15px;line-height:1.65;margin:15px 0 22px}.tool-actions{display:flex;gap:8px;flex-wrap:wrap}.tool-btn{border:1px solid var(--line);background:var(--panel2);padding:10px 14px;border-radius:10px;font-size:11px}.tool-btn.primary{background:#7560e8;border-color:#7560e8;color:#fff}.tool-content{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:20px;border-top:1px solid var(--line);padding-top:22px}.tool-section{border:1px solid var(--line);border-radius:15px;padding:17px;background:rgba(255,255,255,.022);margin-bottom:12px}.tool-section h2{font:700 14px 'Space Grotesk';margin:0 0 12px}.install-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.install{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px;border:1px solid var(--line);border-radius:11px;background:var(--panel2)}.install b{font-size:11px}.install small{display:block;color:#737b89;font-size:9px;margin-top:2px}.install a{font-size:10px;color:#a99cff;white-space:nowrap}.install.muted{opacity:.8}.readme{white-space:pre-wrap;color:#9ca4b2;font:11px/1.7 ui-monospace,SFMono-Regular,Consolas,monospace;max-height:620px;overflow:auto}.meta-row{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid var(--line);font-size:10px}.meta-row:last-child{border-bottom:0}.meta-row span{color:#737b89}.topics{display:flex;flex-wrap:wrap;gap:5px}.topic{font-size:9px;color:#a295ff;background:rgba(124,92,255,.1);padding:4px 7px;border-radius:6px}.stat-row{display:flex;gap:7px;margin-top:20px;flex-wrap:wrap}.stat{padding:10px 14px;border:1px solid var(--line);border-radius:10px;min-width:95px}.stat b{display:block;font:700 16px 'Space Grotesk'}.stat span{font-size:8px;color:#737b89}.install-note{font-size:10px;color:#737b89;margin-top:10px;line-height:1.5}.tool-loading,.tool-error{text-align:center;padding:100px 20px;color:#7d8593}.tool-error b{display:block;color:var(--text);font-size:15px;margin-bottom:5px}@media(max-width:760px){.tool-page{padding:28px 16px 55px}.tool-content{grid-template-columns:1fr}.install-grid{grid-template-columns:1fr}.tool-title{font-size:46px}.stat{flex:1;min-width:0}}@media(min-width:761px){.tool-page{padding-left:0;padding-right:0}}</style>`;
  const ext=a=>(a?.name||'').toLowerCase();
  function platformAsset(a){const n=ext(a);if(/\.apk$/.test(n))return'Android';if(/\.(dmg|pkg)$/.test(n))return'macOS';if(/\.(exe|msi|msix|appx)$/.test(n))return'Windows';if(/\.(appimage|deb|rpm|flatpak|snap)$/.test(n))return'Linux';return null}
  function assetLinks(releases){const map=new Map();releases.forEach(rel=>(rel.assets||[]).forEach(a=>{const p=platformAsset(a);if(p&&!map.has(p))map.set(p,a)}));return map}
  function hasWeb(r){return Boolean(r.homepage&&/^https?:\/\//i.test(r.homepage))}
  function detectSource(r){const t=((r.name||'')+' '+(r.description||'')+' '+(r.topics||[]).join(' ')).toLowerCase();return /source|build|compile|developer|library|framework|cli/.test(t)}
  function health(r,releases){let s=0;s+=Math.min(25,Math.log10(1+(r.stargazers_count||0))*5);s+=Math.min(20,Math.log10(1+(r.forks_count||0))*4);s+=r.license?15:5;s+=r.description?10:2;s+=(r.topics||[]).length?10:3;s+=releases.length?20:5;return Math.min(100,Math.round(s))}
  function installs(r,releases){const assets=assetLinks(releases),out=[];for(const p of ['Android','macOS','Windows','Linux']){const a=assets.get(p);if(a)out.push([p,a.browser_download_url,'Download '+a.name])}if(hasWeb(r))out.push(['Web app',r.homepage,'Open official web app']);if(!out.length){out.push(['GitHub',r.html_url,'Source / installation']);return out}if(detectSource(r)&&!assets.size)out.push(['Source / build',r.html_url,'Build from source']);else out.push(['GitHub',r.html_url,'Source & releases']);return out}
  async function load(){if(!owner||!name){root.innerHTML=styles+'<div class="tool-error"><b>Tool not found</b><p>Open a tool from the directory.</p></div>';return}try{const key='os-tool-'+owner+'/'+name;const cached=sessionStorage.getItem(key);if(cached){try{render(...JSON.parse(cached));}catch{}}const [r,readme,releases]=await Promise.all([get(`/repos/${owner}/${name}`),get(`/repos/${owner}/${name}/readme`).catch(()=>null),get(`/repos/${owner}/${name}/releases?per_page=5`).catch(()=>[])]);sessionStorage.setItem(key,JSON.stringify([r,readme,releases]));render(r,readme,releases)}catch(e){if(!root.querySelector('.tool-page'))root.innerHTML=styles+`<div class="tool-error"><b>Could not load tool</b><p>${esc(e.message)}</p></div>`}}
  function render(r,readme,releases){const list=installs(r,releases),topics=r.topics||[];document.title=`${r.name} — Open Source Explorer`;root.innerHTML=styles+`<div class="tool-page"><section class="tool-hero"><div class="tool-kicker">OPEN SOURCE</div><h1 class="tool-title">${esc(r.name)}</h1><div class="tool-full">${esc(r.full_name)} · ${esc(r.license?.spdx||r.license?.name||'License not detected')}</div><p class="tool-desc">${esc(r.description||'Open-source project from GitHub.')}</p><div class="tool-actions"><a class="tool-btn primary" href="${esc(r.html_url)}" target="_blank" rel="noopener">Jump to GitHub ↗</a><button class="tool-btn" id="cloneBtn">Copy clone URL</button>${r.homepage?`<a class="tool-btn" href="${esc(r.homepage)}" target="_blank" rel="noopener">Official website ↗</a>`:''}</div><div class="stat-row"><div class="stat"><b>${fmt(r.stargazers_count)}</b><span>Stars</span></div><div class="stat"><b>${fmt(r.forks_count)}</b><span>Forks</span></div><div class="stat"><b>${health(r,releases)}%</b><span>Health</span></div></div></section><div class="tool-content"><main><section class="tool-section"><h2>Get the tool</h2><div class="install-grid">${list.map(([label,url,note])=>`<div class="install"><div><b>${esc(label)}</b><small>${esc(note)}</small></div><a href="${esc(url)}" target="_blank" rel="noopener">${label==='GitHub'||label==='Source / build'?'Open ↗':'Download ↗'}</a></div>`).join('')}</div><div class="install-note">Installers are taken from the project's latest GitHub releases. Platforms without a real installer are not shown.</div></section><section class="tool-section"><h2>README</h2><div class="readme">${esc(readme?text(atob(readme.content.replace(/\n/g,''))):'README is not available.')}</div></section></main><aside><section class="tool-section"><h2>Details</h2><div class="meta-row"><span>Language</span><b>${esc(r.language||'—')}</b></div><div class="meta-row"><span>Issues</span><b>${fmt(r.open_issues_count)}</b></div><div class="meta-row"><span>Size</span><b>${fmt(r.size)} KB</b></div><div class="meta-row"><span>Branch</span><b>${esc(r.default_branch||'—')}</b></div><h2 style="margin-top:18px">Topics</h2><div class="topics">${topics.length?topics.map(t=>`<span class="topic">#${esc(t)}</span>`).join(''):'No topics'}</div></section><section class="tool-section"><h2>Releases</h2>${releases.length?releases.slice(0,5).map(x=>`<div class="meta-row"><span>${esc(x.tag_name||x.name)}</span><a href="${esc(x.html_url)}" target="_blank" rel="noopener">View ↗</a></div>`).join(''):'<div class="meta-row"><span>No releases found</span></div>'}</section></aside></div></div>`;document.getElementById('cloneBtn').onclick=async()=>{try{await navigator.clipboard.writeText(r.clone_url);const b=document.getElementById('cloneBtn');b.textContent='Copied ✓';setTimeout(()=>b.textContent='Copy clone URL',1400)}catch{}}}
  load();
})();