(() => {
  const KEY='os-saved', CMP='os-compare';
  const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]').map(Number)}catch{return[]}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify([...new Set(v)]));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=n=>n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(n>=1e5?0:1)+'k':String(n||0);
  const repos=()=>{try{return JSON.parse(localStorage.getItem('open-source-explorer-v2')||'{}').items||[]}catch{return[]}};
  const toast=m=>{const t=document.querySelector('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}};
  const style=document.createElement('style');style.textContent=`
    .compare-tray{position:fixed;z-index:45;left:50%;bottom:18px;transform:translateX(-50%);width:min(900px,calc(100% - 24px));padding:10px 12px;border:1px solid rgba(255,255,255,.12);border-radius:18px;background:rgba(12,14,20,.86);backdrop-filter:blur(22px);box-shadow:0 20px 70px #0008;display:flex;align-items:center;gap:10px}.compare-tray.hidden{display:none}.compare-tray-title{font-size:11px;font-weight:800;white-space:nowrap}.compare-pills{display:flex;gap:7px;flex:1;overflow:auto}.compare-pill{display:flex;align-items:center;gap:6px;padding:7px 9px;border-radius:10px;background:rgba(255,255,255,.07);font-size:10px;white-space:nowrap}.compare-pill button{border:0;background:none;color:#9ba3b2;cursor:pointer}.compare-go{border:0;border-radius:10px;padding:9px 13px;background:#7560e8;color:#fff;font-weight:800;font-size:10px;cursor:pointer}.compare-modal{position:fixed;inset:0;z-index:70;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(2,3,6,.82);backdrop-filter:blur(18px)}.compare-modal.open{display:flex}.compare-sheet{width:min(1000px,100%);max-height:90vh;overflow:auto;border:1px solid rgba(255,255,255,.12);border-radius:24px;background:#0d1016;box-shadow:0 35px 100px #000c}.compare-head{display:flex;justify-content:space-between;align-items:center;padding:20px 22px;border-bottom:1px solid rgba(255,255,255,.08)}.compare-head h3{margin:0;font:700 20px 'Space Grotesk'}.compare-close{border:0;background:rgba(255,255,255,.06);color:#fff;border-radius:10px;width:36px;height:36px}.compare-table{width:100%;border-collapse:collapse;font-size:11px}.compare-table th,.compare-table td{padding:13px 15px;text-align:left;border-bottom:1px solid rgba(255,255,255,.07)}.compare-table th{font-weight:800}.compare-table td:first-child{color:#778092;font-weight:700;width:130px}.compare-repo-name{font-weight:800;color:#fff}.compare-link{color:#a69af2}.light .compare-tray{background:rgba(255,255,255,.9)}.light .compare-sheet{background:#fff;color:#111}.light .compare-head{border-color:rgba(0,0,0,.08)}.light .compare-table th,.light .compare-table td{border-color:rgba(0,0,0,.08)}.light .compare-repo-name{color:#111}@media(max-width:650px){.compare-tray{bottom:8px}.compare-go{padding:8px}.compare-tray-title{display:none}.compare-sheet{border-radius:18px}.compare-table th,.compare-table td{padding:11px 9px;font-size:10px}}
  `;document.head.appendChild(style);
  function tray(){let el=document.querySelector('.compare-tray');if(!el){el=document.createElement('div');el.className='compare-tray hidden';document.body.appendChild(el)}const ids=read(CMP),rs=ids.map(id=>repos().find(r=>Number(r.id)===id)).filter(Boolean);el.innerHTML=`<b class="compare-tray-title">Compare</b><div class="compare-pills">${rs.map(r=>`<span class="compare-pill">${esc(r.full_name)} <button data-remove-compare="${r.id}">×</button></span>`).join('')||'<span class="compare-pill">Select up to 3 repositories</span>'}</div><button class="compare-go" ${rs.length<2?'disabled':''}>Compare ${rs.length}</button>`;el.classList.toggle('hidden',rs.length<1);el.querySelector('.compare-go')?.addEventListener('click',()=>openCompare(rs));el.querySelectorAll('[data-remove-compare]').forEach(b=>b.onclick=()=>{write(CMP,ids.filter(x=>x!==Number(b.dataset.removeCompare)));refresh()})}
  function refresh(){document.querySelectorAll('[data-save]').forEach(b=>{const on=read(KEY).includes(Number(b.dataset.save));b.classList.toggle('active',on);b.textContent=on?'♥ Save':'♡ Save'});document.querySelectorAll('[data-compare]').forEach(b=>{const on=read(CMP).includes(Number(b.dataset.compare));b.classList.toggle('active',on);b.textContent=on?'✓ Compare':'＋ Compare'});tray()}
  function openCompare(rs){if(rs.length<2)return;let m=document.querySelector('.compare-modal');if(!m){m=document.createElement('div');m.className='compare-modal';document.body.appendChild(m)}const rows=[['Platform',r=>r._platform||'Cross-platform'],['Category',r=>r._category||'Utilities'],['Language',r=>r.language||'—'],['Stars',r=>fmt(r.stargazers_count)],['Forks',r=>fmt(r.forks_count)],['Watchers',r=>fmt(r.watchers_count)],['Created',r=>new Date(r.created_at).getFullYear()],['Updated',r=>r.pushed_at?new Date(r.pushed_at).toLocaleDateString():'—']];m.innerHTML=`<div class="compare-sheet"><div class="compare-head"><h3>Repository comparison</h3><button class="compare-close">×</button></div><table class="compare-table"><thead><tr><th>Metric</th>${rs.map(r=>`<th><span class="compare-repo-name">${esc(r.full_name)}</span></th>`).join('')}</tr></thead><tbody>${rows.map(([label,fn])=>`<tr><td>${label}</td>${rs.map(r=>`<td>${esc(fn(r))}</td>`).join('')}</tr>`).join('')}<tr><td>Repository</td>${rs.map(r=>`<td><a class="compare-link" href="${esc(r.html_url)}" target="_blank" rel="noopener">Open GitHub ↗</a></td>`).join('')}</tr></tbody></table></div>`;m.classList.add('open');m.querySelector('.compare-close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')}}
  document.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save){const id=Number(save.dataset.save),a=read(KEY);write(KEY,a.includes(id)?a.filter(x=>x!==id):[...a,id]);toast(a.includes(id)?'Removed from saved':'Saved repository');refresh();return}const cmp=e.target.closest('[data-compare]');if(cmp){const id=Number(cmp.dataset.compare),a=read(CMP);if(a.includes(id)){write(CMP,a.filter(x=>x!==id));toast('Removed from comparison')}else if(a.length>=3){toast('Compare supports up to 3 repositories')}else{write(CMP,[...a,id]);toast('Added to comparison')}refresh()}});
  window.addEventListener('storage',refresh);window.addEventListener('load',refresh);setTimeout(refresh,800);
})();